---
Title: "Presentation: type_1 error"
author: ""
date: ""
---

```{r, include=F}
devtools::load_all()
library(parallel)
load("sim_type1_1004.RData")
load("sim_type1_1005.RData")
load("sim_type1_1006.RData") # simulation/rmd/

m_size <- matrix(NA, nrow = 4, ncol = 2)
m_sigma2_mse <- matrix(NA, nrow = 4, ncol = 1)
m_time <- matrix(NA, nrow = 4, ncol = 3)
```

```{r, 1004f, include=F}
# fast.tn = T, semi.iter = T
m_size[1, ] <- sim_type1_1004[[1]]
m_sigma2_mse[1, ] <- sim_type1_1004[[2]]
m_time[1, ] <- rowMeans(matrix(unlist(sim_type1_1004[[3]]), nrow = 3))
```

```{r, 1005f, include=F}
# fast.tn = T, semi.iter = F
m_size[2, ] <- sim_type1_1005[[1]]
m_sigma2_mse[2, ] <- sim_type1_1005[[2]]
m_time[2, ] <- rowMeans(matrix(unlist(sim_type1_1005[[3]]), nrow = 3))
```

```{r, 1006f, include=F}
# fast.tn = T, semi.iter = F
m_size[3, ] <- sim_type1_1006[[1]]
m_sigma2_mse[3, ] <- sim_type1_1006[[2]]
m_time[3, ] <- rowMeans(matrix(unlist(sim_type1_1006[[3]]), nrow = 3))
```

```{r, summary 100 fix}
print("summary for 100 fixed")
m_size
m_sigma2_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, center1004f, include=F}
load("center_1004.RData")  # simulation/rmd/
m_size[1, ] <- center_1004[[1]]
m_sigma2_mse[1, ] <- center_1004[[2]]
m_c0_mse[1, ] <- center_1004[[3]]
m_calt_mse[1, ] <- center_1004[[4]]
m_time[1, ] <- rowMeans(matrix(unlist(center_1004[[5]]), nrow = 3))
```

```{r, center1007f, include=F}
load("center_1007.RData")  # simulation/rmd/
m_size[2, ] <- center_1007[[1]]
m_sigma2_mse[2, ] <- center_1007[[2]]
m_c0_mse[2, ] <- center_1007[[3]]
m_calt_mse[2, ] <- center_1007[[4]]
m_time[2, ] <- rowMeans(matrix(unlist(center_1007[[5]]), nrow = 3))
```

```{r, summary center100f}
print("summary for 100 fix center")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, sim_1004r, include=F}
load("sim_type1_1004r.RData") # simulation/rmd/
m_size[1, ] <- (sim_type1_1004[[1]][[1]] + sim_type1_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (sim_type1_1004[[1]][[2]] + sim_type1_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (sim_type1_1004[[1]][[3]] + sim_type1_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (sim_type1_1004[[1]][[4]] + sim_type1_1004[[2]][[4]]) / 2
m_time[1, ] <- (sim_type1_1004[[1]][[5]] + sim_type1_1004[[2]][[5]]) / 2
```
```{r, sim_1007r, include=F}
load("sim_type1_1007.RData") # simulation/rmd/
m_size[2, ] <- (sim_type1_1007[[1]][[1]] + sim_type1_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (sim_type1_1007[[1]][[2]] + sim_type1_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (sim_type1_1007[[1]][[3]] + sim_type1_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (sim_type1_1007[[1]][[4]] + sim_type1_1007[[2]][[4]]) / 2
m_time[2, ] <- (sim_type1_1007[[1]][[5]] + sim_type1_1007[[2]][[5]]) / 2
```

```{r, summary default 100r}
print("summary for 100 random")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```

```{r, sim_5004r.bs, eval = F, include = F}
load("simulation/rmd/sim_type1_5004_1r.RData") # simulation/rmd/
load("simulation/rmd/sim_type1_5004_2r.RData")
load("simulation/rmd/sim_type1_5004_3r.RData")
load("simulation/rmd/sim_type1_5004_4r.RData")
load("simulation/rmd/sim_type1_5004_5r.RData")
sim_type1_5004 <- c(sim_type1_5004_1, sim_type1_5004_2, sim_type1_5004_3, sim_type1_5004_4, sim_type1_5004_5)
for (i in seq_along(sim_type1_5004)) {
    m_size[1, ] <- m_size[1, ] + sim_type1_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + sim_type1_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + sim_type1_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + sim_type1_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + sim_type1_5004[[i]][[5]]
}
seed.bs <- sapply(sim_type1_5004, seed <- function(l_list) {
    l_list[[6]]
})
sim_type1_5004r <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(sim_type1_5004r, file = "sim_type1_5004r.RData")
```

```{r, sim_5007r.bs, eval = F, include = F}
load("simulation/rmd/sim_type1_5007_1r.RData") # simulation/rmd/
load("simulation/rmd/sim_type1_5007_2r.RData")
load("simulation/rmd/sim_type1_5007_3r.RData")
load("simulation/rmd/sim_type1_5007_4r.RData")
load("simulation/rmd/sim_type1_5007_5r.RData")
sim_type1_5007 <- c(sim_type1_5007_1, sim_type1_5007_2, sim_type1_5007_3, sim_type1_5007_4, sim_type1_5007_5)
for (i in seq_along(sim_type1_5007)) {
    m_size[2, ] <- m_size[2, ] + sim_type1_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + sim_type1_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + sim_type1_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + sim_type1_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + sim_type1_5007[[i]][[5]]
}
seed.bs <- sapply(sim_type1_5007, seed <- function(l_list) {
    l_list[[6]]
})
sim_type1_5007r <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(sim_type1_5007r, file = "sim_type1_5007r.RData")
```

```{r, sim_5004r, include = F}
load("sim_type1_5004r.RData") # simulation/rmd/
m_size[1, ] <- sim_type1_5004r[[1]] / 10
m_sigma2_mse[1, ] <- sim_type1_5004r[[2]] / 10
m_c0_mse[1, ] <- sim_type1_5004r[[3]] / 10
m_calt_mse[1, ] <- sim_type1_5004r[[4]] / 10
m_time[1, ] <- sim_type1_5004r[[5]] / 10
```
```{r, sim_5007r, include = F}
load("sim_type1_5007r.RData") # simulation/rmd/
m_size[2, ] <- sim_type1_5007r[[1]] / 10
m_sigma2_mse[2, ] <- sim_type1_5007r[[2]] / 10
m_c0_mse[2, ] <- sim_type1_5007r[[3]] / 10
m_calt_mse[2, ] <- sim_type1_5007r[[4]] / 10
m_time[2, ] <- sim_type1_5007r[[5]] / 10
```

```{r, summary sim_500r}
print("summary for 500 random")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```


```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, center_1004r, include=F}
load("center_1004r.RData") # simulation/rmd/
m_size[1, ] <- (center_1004[[1]][[1]] + center_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (center_1004[[1]][[2]] + center_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (center_1004[[1]][[3]] + center_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (center_1004[[1]][[4]] + center_1004[[2]][[4]]) / 2
m_time[1, ] <- (center_1004[[1]][[5]] + center_1004[[2]][[5]]) / 2
```
```{r, center_1007r, include=F}
load("center_1007r.RData") # simulation/rmd/
m_size[2, ] <- (center_1007[[1]][[1]] + center_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (center_1007[[1]][[2]] + center_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (center_1007[[1]][[3]] + center_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (center_1007[[1]][[4]] + center_1007[[2]][[4]]) / 2
m_time[2, ] <- (center_1007[[1]][[5]] + center_1007[[2]][[5]]) / 2
```

```{r, summary center_100r}
print("summary for 100 random center")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, sim_5004d.bs, eval = F, include = F}
load("simulation/rmd/sim_type1_5004_1d.RData") # simulation/rmd/
load("simulation/rmd/sim_type1_5004_2d.RData")
load("simulation/rmd/sim_type1_5004_3d.RData")
load("simulation/rmd/sim_type1_5004_4d.RData")
load("simulation/rmd/sim_type1_5004_5d.RData")
sim_type1_5004 <- c(sim_type1_5004_1, sim_type1_5004_2, sim_type1_5004_3, sim_type1_5004_4, sim_type1_5004_5)
for (i in seq_along(sim_type1_5004)) {
    m_size[1, ] <- m_size[1, ] + sim_type1_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + sim_type1_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + sim_type1_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + sim_type1_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + sim_type1_5004[[i]][[5]]
}
seed.bs <- sapply(sim_type1_5004, seed <- function(l_list) {
    l_list[[6]]
})
sim_type1_5004d <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(sim_type1_5004d, file = "sim_type1_5004d.RData")
```
```{r, sim_5007d.bs, eval = F, include = F}
load("simulation/rmd/sim_type1_5007_1d.RData") # simulation/rmd/
load("simulation/rmd/sim_type1_5007_2d.RData")
load("simulation/rmd/sim_type1_5007_3d.RData")
load("simulation/rmd/sim_type1_5007_4d.RData")
load("simulation/rmd/sim_type1_5007_5d.RData")
sim_type1_5007 <- c(sim_type1_5007_1, sim_type1_5007_2, sim_type1_5007_3, sim_type1_5007_4, sim_type1_5007_5)
for (i in seq_along(sim_type1_5007)) {
    m_size[2, ] <- m_size[2, ] + sim_type1_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + sim_type1_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + sim_type1_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + sim_type1_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + sim_type1_5007[[i]][[5]]
}
seed.bs <- sapply(sim_type1_5007, seed <- function(l_list) {
    l_list[[6]]
})
sim_type1_5007d <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(sim_type1_5007d, file = "sim_type1_5007d.RData")
```
```{r, sim_5004d, include = F}
load("sim_type1_5004d.RData") # simulation/rmd/
m_size[1, ] <- sim_type1_5004d[[1]] / 10
m_sigma2_mse[1, ] <- sim_type1_5004d[[2]] / 10
m_c0_mse[1, ] <- sim_type1_5004d[[3]] / 10
m_calt_mse[1, ] <- sim_type1_5004d[[4]] / 10
m_time[1, ] <- sim_type1_5004d[[5]] / 10
```
```{r, sim_5007d, include = F}
load("sim_type1_5007d.RData") # simulation/rmd/
m_size[2, ] <- sim_type1_5007d[[1]] / 10
m_sigma2_mse[2, ] <- sim_type1_5007d[[2]] / 10
m_c0_mse[2, ] <- sim_type1_5007d[[3]] / 10
m_calt_mse[2, ] <- sim_type1_5007d[[4]] / 10
m_time[2, ] <- sim_type1_5007d[[5]] / 10
```
```{r, summary sim_500d}
print("summary for 500 d")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```


```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, center_5004d.bs, eval = F, include = F}
load("simulation/rmd/center_5004_1d.RData") # simulation/rmd/
load("simulation/rmd/center_5004_2d.RData")
load("simulation/rmd/center_5004_3d.RData")
load("simulation/rmd/center_5004_4d.RData")
load("simulation/rmd/center_5004_5d.RData")
center_5004 <- c(center_5004_1, center_5004_2, center_5004_3, center_5004_4, center_5004_5)
for (i in seq_along(center_5004)) {
    m_size[1, ] <- m_size[1, ] + center_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + center_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + center_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + center_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + center_5004[[i]][[5]]
}
seed.bs <- sapply(center_5004, seed <- function(l_list) {
    l_list[[6]]
})
center_5004d <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(center_5004d, file = "center_5004d.RData")
```
```{r, center_5007d.bs, eval = F, include = F}
load("simulation/rmd/center_5007_1d.RData") # simulation/rmd/
load("simulation/rmd/center_5007_2d.RData")
load("simulation/rmd/center_5007_3d.RData")
load("simulation/rmd/center_5007_4d.RData")
load("simulation/rmd/center_5007_5d.RData")
center_5007 <- c(center_5007_1, center_5007_2, center_5007_3, center_5007_4, center_5007_5)
for (i in seq_along(center_5007)) {
    m_size[2, ] <- m_size[2, ] + center_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + center_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + center_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + center_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + center_5007[[i]][[5]]
}
seed.bs <- sapply(center_5007, seed <- function(l_list) {
    l_list[[6]]
})
center_5007d <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(center_5007d, file = "center_5007d.RData")
```

```{r, center_5004d, include = F}
load("center_5004d.RData") # simulation/rmd/
m_size[1, ] <- center_5004d[[1]] / 10
m_sigma2_mse[1, ] <- center_5004d[[2]] / 10
m_c0_mse[1, ] <- center_5004d[[3]] / 10
m_calt_mse[1, ] <- center_5004d[[4]] / 10
m_time[1, ] <- center_5004d[[5]] / 10
```
```{r, center_5007d, include = F}
load("center_5007d.RData") # simulation/rmd/
m_size[2, ] <- center_5007d[[1]] / 10
m_sigma2_mse[2, ] <- center_5007d[[2]] / 10
m_c0_mse[2, ] <- center_5007d[[3]] / 10
m_calt_mse[2, ] <- center_5007d[[4]] / 10
m_time[2, ] <- center_5007d[[5]] / 10
```

```{r, summary center_500d}
print("summary for center 500 d")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```
```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, sim_1004d, include=F}
load("sim_type1_1004d.RData") # simulation/rmd/
m_size[1, ] <- (sim_type1_1004[[1]][[1]] + sim_type1_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (sim_type1_1004[[1]][[2]] + sim_type1_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (sim_type1_1004[[1]][[3]] + sim_type1_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (sim_type1_1004[[1]][[4]] + sim_type1_1004[[2]][[4]]) / 2
m_time[1, ] <- (sim_type1_1004[[1]][[5]] + sim_type1_1004[[2]][[5]]) / 2
```
```{r, sim_1007d, include=F}
load("sim_type1_1007d.RData") # simulation/rmd/
m_size[2, ] <- (sim_type1_1007[[1]][[1]] + sim_type1_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (sim_type1_1007[[1]][[2]] + sim_type1_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (sim_type1_1007[[1]][[3]] + sim_type1_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (sim_type1_1007[[1]][[4]] + sim_type1_1007[[2]][[4]]) / 2
m_time[2, ] <- (sim_type1_1007[[1]][[5]] + sim_type1_1007[[2]][[5]]) / 2
```

```{r, summary sim 100d}
print("summary for 100 d")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```


```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, center_1004d, include=F}
load("center_1004d.RData") # simulation/rmd/
m_size[1, ] <- (center_1004[[1]][[1]] + center_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (center_1004[[1]][[2]] + center_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (center_1004[[1]][[3]] + center_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (center_1004[[1]][[4]] + center_1004[[2]][[4]]) / 2
m_time[1, ] <- (center_1004[[1]][[5]] + center_1004[[2]][[5]]) / 2
```
```{r, center_1007d, include=F}
load("center_1007d.RData") # simulation/rmd/
m_size[2, ] <- (center_1007[[1]][[1]] + center_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (center_1007[[1]][[2]] + center_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (center_1007[[1]][[3]] + center_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (center_1007[[1]][[4]] + center_1007[[2]][[4]]) / 2
m_time[2, ] <- (center_1007[[1]][[5]] + center_1007[[2]][[5]]) / 2
```
```{r, summary center 100d}
print("summary for 100 d center")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, sim_1007t, include=F}
load("sim_type1_1007t.RData") # simulation/rmd/
m_size[2, ] <- (sim_type1_1007[[1]][[1]] + sim_type1_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (sim_type1_1007[[1]][[2]] + sim_type1_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (sim_type1_1007[[1]][[3]] + sim_type1_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (sim_type1_1007[[1]][[4]] + sim_type1_1007[[2]][[4]]) / 2
m_time[2, ] <- (sim_type1_1007[[1]][[5]] + sim_type1_1007[[2]][[5]]) / 2
```
```{r, sim_1004t, include=F}
load("sim_type1_1004t.RData") # simulation/rmd/
m_size[1, ] <- (sim_type1_1004[[1]][[1]] + sim_type1_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (sim_type1_1004[[1]][[2]] + sim_type1_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (sim_type1_1004[[1]][[3]] + sim_type1_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (sim_type1_1004[[1]][[4]] + sim_type1_1004[[2]][[4]]) / 2
m_time[1, ] <- (sim_type1_1004[[1]][[5]] + sim_type1_1004[[2]][[5]]) / 2
```
```{r, summary sim 100t}
print("summary for 100 truncate")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```

```{r, center_1004t, include=F}
load("center_1004t.RData") # simulation/rmd/
m_size[1, ] <- (center_1004[[1]][[1]] + center_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (center_1004[[1]][[2]] + center_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (center_1004[[1]][[3]] + center_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (center_1004[[1]][[4]] + center_1004[[2]][[4]]) / 2
m_time[1, ] <- (center_1004[[1]][[5]] + center_1004[[2]][[5]]) / 2
```
```{r, center_1007t, include=F}
load("center_1007t.RData") # simulation/rmd/
m_size[2, ] <- (center_1007[[1]][[1]] + center_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (center_1007[[1]][[2]] + center_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (center_1007[[1]][[3]] + center_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (center_1007[[1]][[4]] + center_1007[[2]][[4]]) / 2
m_time[2, ] <- (center_1007[[1]][[5]] + center_1007[[2]][[5]]) / 2
```

```{r, summary center 100t}
print("summary for 100 t center")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, sim_5004t.bs, eval = F, include = F}
load("simulation/rmd/sim_type1_5004_1d.RData") # simulation/rmd/
load("simulation/rmd/sim_type1_5004_2d.RData")
load("simulation/rmd/sim_type1_5004_3d.RData")
load("simulation/rmd/sim_type1_5004_4d.RData")
load("simulation/rmd/sim_type1_5004_5d.RData")
sim_type1_5004 <- c(sim_type1_5004_1, sim_type1_5004_2, sim_type1_5004_3, sim_type1_5004_4, sim_type1_5004_5)
for (i in seq_along(sim_type1_5004)) {
    m_size[1, ] <- m_size[1, ] + sim_type1_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + sim_type1_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + sim_type1_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + sim_type1_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + sim_type1_5004[[i]][[5]]
}
seed.bs <- sapply(sim_type1_5004, seed <- function(l_list) {
    l_list[[6]]
})
sim_type1_5004t <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(sim_type1_5004t, file = "sim_type1_5004t.RData")
```
```{r, sim_5007t.bs, eval = F, include = F}
load("simulation/rmd/sim_type1_5007_1d.RData") # simulation/rmd/
load("simulation/rmd/sim_type1_5007_2d.RData")
load("simulation/rmd/sim_type1_5007_3d.RData")
load("simulation/rmd/sim_type1_5007_4d.RData")
load("simulation/rmd/sim_type1_5007_5d.RData")
sim_type1_5007 <- c(sim_type1_5007_1, sim_type1_5007_2, sim_type1_5007_3, sim_type1_5007_4, sim_type1_5007_5)
for (i in seq_along(sim_type1_5007)) {
    m_size[2, ] <- m_size[2, ] + sim_type1_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + sim_type1_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + sim_type1_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + sim_type1_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + sim_type1_5007[[i]][[5]]
}
seed.bs <- sapply(sim_type1_5007, seed <- function(l_list) {
    l_list[[6]]
})
sim_type1_5007t <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(sim_type1_5007t, file = "sim_type1_5007t.RData")
```
```{r, sim_5004t, include = F}
# load("sim_type1_5004t.RData") # simulation/rmd/
# m_size[1, ] <- sim_type1_5004t[[1]] / 10
# m_sigma2_mse[1, ] <- sim_type1_5004t[[2]] / 10
# m_c0_mse[1, ] <- sim_type1_5004t[[3]] / 10
# m_calt_mse[1, ] <- sim_type1_5004t[[4]] / 10
# m_time[1, ] <- sim_type1_5004t[[5]] / 10
```
```{r, sim_5007t, include = F}
load("sim_type1_5007t.RData") # simulation/rmd/
m_size[2, ] <- sim_type1_5007t[[1]] / 10
m_sigma2_mse[2, ] <- sim_type1_5007t[[2]] / 10
m_c0_mse[2, ] <- sim_type1_5007t[[3]] / 10
m_calt_mse[2, ] <- sim_type1_5007t[[4]] / 10
m_time[2, ] <- sim_type1_5007t[[5]] / 10
```
```{r, summary sim_500t}
print("summary for 500 t")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```


```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, center_5004tt, eval = F, include = F}
load("simulation/rmd/center_5004_1t.RData") # simulation/rmd/
load("simulation/rmd/center_5004_2t.RData")
load("simulation/rmd/center_5004_3t.RData")
load("simulation/rmd/center_5004_4t.RData")
load("simulation/rmd/center_5004_5t.RData")
center_5004 <- c(center_5004_1, center_5004_2, center_5004_3, center_5004_4, center_5004_5)
for (i in seq_along(center_5004)) {
    m_size[1, ] <- m_size[1, ] + center_5004[[i]][[1]]
    m_sigma2_mse[1, ] <- m_sigma2_mse[1, ] + center_5004[[i]][[2]]
    m_c0_mse[1, ] <- m_c0_mse[1, ] + center_5004[[i]][[3]]
    m_calt_mse[1, ] <- m_calt_mse[1, ] + center_5004[[i]][[4]]
    m_time[1, ] <- m_time[1, ] + center_5004[[i]][[5]]
}
seed.bs <- sapply(center_5004, seed <- function(l_list) {
    l_list[[6]]
})
center_5004t <- list(
    m_size[1, ],
    m_sigma2_mse[1, ],
    m_c0_mse[1, ],
    m_calt_mse[1, ],
    m_time[1, ],
    seed.bs
)
save(center_5004t, file = "center_5004t.RData")
```
```{r, center_5007tt, eval = F, include = F}
load("simulation/rmd/center_5007_1t.RData") # simulation/rmd/
load("simulation/rmd/center_5007_2t.RData")
load("simulation/rmd/center_5007_3t.RData")
load("simulation/rmd/center_5007_4t.RData")
load("simulation/rmd/center_5007_5t.RData")
center_5007 <- c(center_5007_1, center_5007_2, center_5007_3, center_5007_4, center_5007_5)
for (i in seq_along(center_5007)) {
    m_size[2, ] <- m_size[2, ] + center_5007[[i]][[1]]
    m_sigma2_mse[2, ] <- m_sigma2_mse[2, ] + center_5007[[i]][[2]]
    m_c0_mse[2, ] <- m_c0_mse[2, ] + center_5007[[i]][[3]]
    m_calt_mse[2, ] <- m_calt_mse[2, ] + center_5007[[i]][[4]]
    m_time[2, ] <- m_time[2, ] + center_5007[[i]][[5]]
}
seed.bs <- sapply(center_5007, seed <- function(l_list) {
    l_list[[6]]
})
center_5007t <- list(
    m_size[2, ],
    m_sigma2_mse[2, ],
    m_c0_mse[2, ],
    m_calt_mse[2, ],
    m_time[2, ],
    seed.bs
)
save(center_5007t, file = "center_5007t.RData")
```

```{r, center_5004t, include = F}
load("center_5004t.RData") # simulation/rmd/
m_size[1, ] <- center_5004t[[1]] / 10
m_sigma2_mse[1, ] <- center_5004t[[2]] / 10
m_c0_mse[1, ] <- center_5004t[[3]] / 10
m_calt_mse[1, ] <- center_5004t[[4]] / 10
m_time[1, ] <- center_5004t[[5]] / 10
```
```{r, center_5007t, include = F}
load("center_5007t.RData") # simulation/rmd/
m_size[2, ] <- center_5007t[[1]] / 10
m_sigma2_mse[2, ] <- center_5007t[[2]] / 10
m_c0_mse[2, ] <- center_5007t[[3]] / 10
m_calt_mse[2, ] <- center_5007t[[4]] / 10
m_time[2, ] <- center_5007t[[5]] / 10
```

```{r, summary center_500t}
print("summary for center 500 t")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, sim_1004z, include=F}
load("sim_type1_1004z.RData") # simulation/rmd/
m_size[1, ] <- (sim_type1_1004[[1]][[1]] + sim_type1_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (sim_type1_1004[[1]][[2]] + sim_type1_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (sim_type1_1004[[1]][[3]] + sim_type1_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (sim_type1_1004[[1]][[4]] + sim_type1_1004[[2]][[4]]) / 2
m_time[1, ] <- (sim_type1_1004[[1]][[5]] + sim_type1_1004[[2]][[5]]) / 2
```
```{r, sim_1007Z, include=F}
load("sim_type1_1007z.RData") # simulation/rmd/
m_size[2, ] <- (sim_type1_1007[[1]][[1]] + sim_type1_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (sim_type1_1007[[1]][[2]] + sim_type1_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (sim_type1_1007[[1]][[3]] + sim_type1_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (sim_type1_1007[[1]][[4]] + sim_type1_1007[[2]][[4]]) / 2
m_time[2, ] <- (sim_type1_1007[[1]][[5]] + sim_type1_1007[[2]][[5]]) / 2
```

```{r, summary  100z}
print("summary for 100 zero")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, center_1004z, include=F}
load("center_1004z.RData") # simulation/rmd/
m_size[1, ] <- (center_1004[[1]][[1]] + center_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (center_1004[[1]][[2]] + center_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (center_1004[[1]][[3]] + center_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (center_1004[[1]][[4]] + center_1004[[2]][[4]]) / 2
m_time[1, ] <- (center_1004[[1]][[5]] + center_1004[[2]][[5]]) / 2
```
```{r, center_1007z, include=F}
load("center_1007z.RData") # simulation/rmd/
m_size[2, ] <- (center_1007[[1]][[1]] + center_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (center_1007[[1]][[2]] + center_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (center_1007[[1]][[3]] + center_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (center_1007[[1]][[4]] + center_1007[[2]][[4]]) / 2
m_time[2, ] <- (center_1007[[1]][[5]] + center_1007[[2]][[5]]) / 2
```

```{r, summary center_100z}
print("summary for 100 zero center")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```


```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, sim_1004w, include=F}
load("sim_type1_1004w.RData") # simulation/rmd/
m_size[1, ] <- (sim_type1_1004[[1]][[1]] + sim_type1_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (sim_type1_1004[[1]][[2]] + sim_type1_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (sim_type1_1004[[1]][[3]] + sim_type1_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (sim_type1_1004[[1]][[4]] + sim_type1_1004[[2]][[4]]) / 2
m_time[1, ] <- (sim_type1_1004[[1]][[5]] + sim_type1_1004[[2]][[5]]) / 2
```
```{r, sim_1007w, include=F}
load("sim_type1_1007w.RData") # simulation/rmd/
m_size[2, ] <- (sim_type1_1007[[1]][[1]] + sim_type1_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (sim_type1_1007[[1]][[2]] + sim_type1_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (sim_type1_1007[[1]][[3]] + sim_type1_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (sim_type1_1007[[1]][[4]] + sim_type1_1007[[2]][[4]]) / 2
m_time[2, ] <- (sim_type1_1007[[1]][[5]] + sim_type1_1007[[2]][[5]]) / 2
```

```{r, summary  100w}
print("summary for 100 weighted")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, sim_1004zw, include=F}
load("sim_type1_1004zw.RData") # simulation/rmd/
m_size[1, ] <- (sim_type1_1004[[1]][[1]] + sim_type1_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (sim_type1_1004[[1]][[2]] + sim_type1_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (sim_type1_1004[[1]][[3]] + sim_type1_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (sim_type1_1004[[1]][[4]] + sim_type1_1004[[2]][[4]]) / 2
m_time[1, ] <- (sim_type1_1004[[1]][[5]] + sim_type1_1004[[2]][[5]]) / 2
```
```{r, sim_1007zw, include=F}
load("sim_type1_1007zw.RData") # simulation/rmd/
m_size[2, ] <- (sim_type1_1007[[1]][[1]] + sim_type1_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (sim_type1_1007[[1]][[2]] + sim_type1_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (sim_type1_1007[[1]][[3]] + sim_type1_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (sim_type1_1007[[1]][[4]] + sim_type1_1007[[2]][[4]]) / 2
m_time[2, ] <- (sim_type1_1007[[1]][[5]] + sim_type1_1007[[2]][[5]]) / 2
```

```{r, summary  100zw}
print("summary for 100 zero weighted")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```


```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, center_1004w, include=F}
load("center_1004w.RData") # simulation/rmd/
m_size[1, ] <- (center_1004[[1]][[1]] + center_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (center_1004[[1]][[2]] + center_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (center_1004[[1]][[3]] + center_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (center_1004[[1]][[4]] + center_1004[[2]][[4]]) / 2
m_time[1, ] <- (center_1004[[1]][[5]] + center_1004[[2]][[5]]) / 2
```
```{r, center_1007w, include=F}
load("center_1007w.RData") # simulation/rmd/
m_size[2, ] <- (center_1007[[1]][[1]] + center_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (center_1007[[1]][[2]] + center_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (center_1007[[1]][[3]] + center_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (center_1007[[1]][[4]] + center_1007[[2]][[4]]) / 2
m_time[2, ] <- (center_1007[[1]][[5]] + center_1007[[2]][[5]]) / 2
```

```{r, summary center_100w}
print("summary for 100 weighted center")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```

```{r, include=F}
m_size <- matrix(0, nrow = 2, ncol = 2)
m_sigma2_mse <- matrix(0, nrow = 2, ncol = 1)
m_c0_mse <- matrix(0, nrow = 2, ncol = 1)
m_calt_mse <- matrix(0, nrow = 2, ncol = 1)
m_time <- matrix(0, nrow = 2, ncol = 3)
```
```{r, center_1004zw, include=F}
load("center_1004zw.RData") # simulation/rmd/
m_size[1, ] <- (center_1004[[1]][[1]] + center_1004[[2]][[1]]) / 2
m_sigma2_mse[1, ] <- (center_1004[[1]][[2]] + center_1004[[2]][[2]]) / 2
m_c0_mse[1, ] <- (center_1004[[1]][[3]] + center_1004[[2]][[3]]) / 2
m_calt_mse[1, ] <- (center_1004[[1]][[4]] + center_1004[[2]][[4]]) / 2
m_time[1, ] <- (center_1004[[1]][[5]] + center_1004[[2]][[5]]) / 2
```
```{r, center_1007zw, include=F}
load("center_1007zw.RData") # simulation/rmd/
m_size[2, ] <- (center_1007[[1]][[1]] + center_1007[[2]][[1]]) / 2
m_sigma2_mse[2, ] <- (center_1007[[1]][[2]] + center_1007[[2]][[2]]) / 2
m_c0_mse[2, ] <- (center_1007[[1]][[3]] + center_1007[[2]][[3]]) / 2
m_calt_mse[2, ] <- (center_1007[[1]][[4]] + center_1007[[2]][[4]]) / 2
m_time[2, ] <- (center_1007[[1]][[5]] + center_1007[[2]][[5]]) / 2
```

```{r, summary center_100zw}
print("summary for 100 zero weighted center")
m_size
m_sigma2_mse
m_c0_mse
m_calt_mse
m_time
```